const fontFamilyList = [
  "Arial",
  "Roboto",
  "Young Serif",
  "gothic",
  "Arial Unicode MS",
  "Bagel Fat One",
  "Black And White Picture",
  "Diphylleia",
  "Black Han Sans",
  "Nanum Gothic",
  "Nanum Pen Script",
  "Noto Sans",
  "Noto Sans KR",
  "Noto Serif KR",
  "Gamja Flower",
  "Gasoek One",
  "Grandiflora One",
  "Gugi",
  "Hahmlet",
  "Moirai One",
  "Orbit",
  "Pixelify Sans",
  "Song Myung",
  "Single Day",
  "SF Pro",
  "D2Coding",
  "EliceDigitalBaeum-Bd",
]

export default fontFamilyList
